name: GitHub Actions Demo
on: push

jobs:
  gradle-rc:
    runs-on: ubuntu-latest

    setps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: rc
          arguments: build -x test