name: GitHub Actions Demo
on: push

jobs:
  build:
    runs-on: windows-latest #ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: build -x test
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 11
      # - name: Gradle Command
      #   uses: eskatos/gradle-command-action@v1
      #   with:
      #     gradle-version: rc
      #     arguments: build -x test
